font_family      Hack Nerd Font Mono Regular
# font_family      ProFontWindows Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
# font_size 18.0
adjust_line_height  2

## Catppuccin colors
# color0  #45475A
# color8  #585B70
# color1  #F38BA8
# color9  #F38BA8
# color2  #A6E3A1
# color10 #A6E3A1
# color3  #F9E2AF
# color11 #F9E2AF
# color4  #89B4FA
# color12 #89B4FA
# color5  #F5C2E7
# color13 #F5C2E7
# color6  #94E2D5
# color14 #94E2D5
# color7  #BAC2DE
# color15 #A6ADC8
# foreground #CDD6F4
# background #1E1E2E

## Duck Extra Dark coloes
color0  #282A2E
color1  #A54242
color2  #8C9440
color3  #DE935F
color4  #5F819D
color5  #85678F
color6  #5E8D87
color7  #707880
color8  #373B41
color9  #FF5555
color10 #B5BD68
color11 #F0C674
color12 #81A2BE
color13 #B294BB
color14 #8ABEB7
color15 #C5C8C6
foreground #C5C8C6
# background #1E1E1E
background #000000

## OneShot Dark colors
# color0  #282A2E
# color1  #BC3342
# color2  #A97C41
# color3  #E67B60
# color4  #77659E
# color5  #A45090
# color6  #757488
# color7  #707880
# color8  #373B41
# color9  #FF4256
# color10 #C8AF69
# color11 #F4B975
# color12 #A18DBE
# color13 #C57CBB
# color14 #A7AFB8
# color15 #C5C8C6
# foreground #D4BCC6
# background #1E1E1E

# background_opacity 0.75
# background_tint 0.75
# background_blur 1
